"""
SONAR-GUARD Configuration
=========================
Single source of truth for all system parameters.
Modify this file to adjust system behaviour — do NOT hardcode values in pipeline modules.

Project:   SONAR-GUARD
Team:      ZENVIS | M. Kumarasamy College of Engineering
Event:     Smart India Hackathon 2026 — PS 26057
"""

import os
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional
import torch


# ---------------------------------------------------------------------------
# Root paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).parent.resolve()
DATA_DIR     = PROJECT_ROOT / "data"
MODELS_DIR   = PROJECT_ROOT / "models"
OUTPUTS_DIR  = PROJECT_ROOT / "outputs"
LOGS_DIR     = PROJECT_ROOT / "logs"


@dataclass
class Config:
    """
    Central configuration object for the SONAR-GUARD system.
    All tunable parameters live here.
    """

    # ------------------------------------------------------------------
    # Hardware
    # ------------------------------------------------------------------
    # Auto-detected at runtime — do not hardcode "cuda"
    device: str = field(default_factory=lambda: "cuda" if torch.cuda.is_available() else "cpu")

    # ------------------------------------------------------------------
    # Data paths
    # ------------------------------------------------------------------
    data_raw_dir:        Path = DATA_DIR / "raw"
    data_processed_dir:  Path = DATA_DIR / "processed"
    data_train_dir:      Path = DATA_DIR / "train"
    data_val_dir:        Path = DATA_DIR / "val"
    data_test_dir:       Path = DATA_DIR / "test"
    data_verified_dir:   Path = DATA_DIR / "verified"

    # ------------------------------------------------------------------
    # Model paths
    # ------------------------------------------------------------------
    yolo_model_dir:       Path = MODELS_DIR / "yolo"
    sam_model_dir:        Path = MODELS_DIR / "sam"

    # YOLO pretrained weights to start from (nano by default — CPU-friendly)
    # Options: yolov8n.pt, yolov8s.pt, yolov8m.pt, yolov8l.pt, yolov8x.pt
    yolo_pretrained:      str = "yolov8n.pt"

    # Path to trained/fine-tuned YOLO model (set after training)
    yolo_trained_model:   Optional[Path] = None

    # SAM model variant (requires GPU + extra install — optional)
    sam_checkpoint:       Optional[Path] = None
    sam_model_type:       str = "vit_b"   # vit_b | vit_l | vit_h

    # ------------------------------------------------------------------
    # YOLO training parameters
    # ------------------------------------------------------------------
    model_size:    str   = "n"        # n=nano, s=small, m=medium, l=large, x=xlarge
    img_size:      int   = 640        # Input resolution (pixels)
    epochs:        int   = 50         # Default epochs — increase for real training
    batch_size:    int   = 8          # Small batch for CPU / limited RAM
    learning_rate: float = 0.01
    momentum:      float = 0.937
    weight_decay:  float = 0.0005
    patience:      int   = 20         # Early stopping patience
    workers:       int   = 0          # DataLoader workers (0 = main thread, safe on Windows)
    seed:          int   = 42         # Reproducible training & split

    # YOLO dataset YAML (generated by training pipeline)
    dataset_yaml:  Optional[Path] = None

    # ------------------------------------------------------------------
    # Inference thresholds
    # ------------------------------------------------------------------
    confidence_threshold: float = 0.25   # Minimum detection confidence
    iou_threshold:        float = 0.45   # NMS IoU threshold

    # ------------------------------------------------------------------
    # False Positive Filter parameters
    # ------------------------------------------------------------------
    fp_min_bbox_area_px:    int   = 100    # Reject detections with bbox area below this (px²)
    fp_max_aspect_ratio:    float = 10.0   # Reject detections with extreme aspect ratio
    fp_min_shape_evidence:  float = 0.05   # Reject if shape evidence below this
    fp_min_shadow_evidence: float = 0.0    # Shadow evidence minimum (only used if require_shadow=True)
    fp_require_shadow:      bool  = False  # If True, reject detections with no acoustic shadow

    # ------------------------------------------------------------------
    # Preprocessing parameters
    # ------------------------------------------------------------------
    # Noise reduction
    median_filter_ksize:   int   = 5      # Kernel size for median filter (must be odd)
    gaussian_blur_ksize:   int   = 3      # Gaussian blur kernel (must be odd); 0 = disabled
    gaussian_sigma:        float = 0.0    # 0 = auto-computed from ksize

    # CLAHE (Contrast Limited Adaptive Histogram Equalization)
    use_clahe:             bool  = True
    clahe_clip_limit:      float = 2.0
    clahe_tile_size:       tuple = (8, 8)

    # Output resolution normalization
    target_width:          int   = 640
    target_height:         int   = 640

    # ------------------------------------------------------------------
    # Self-supervised pre-training parameters
    # ------------------------------------------------------------------
    ssl_method:            str   = "simclr"   # simclr | autoencoder | mim
    ssl_epochs:            int   = 30
    ssl_batch_size:        int   = 16
    ssl_lr:                float = 1e-3
    ssl_embedding_dim:     int   = 128
    ssl_temperature:       float = 0.07       # SimCLR temperature

    # ------------------------------------------------------------------
    # Acoustic shadow analysis
    # ------------------------------------------------------------------
    shadow_search_ratio:   float = 0.5        # How far behind target to search
    shadow_intensity_thresh: float = 0.35     # Intensity threshold for shadow region

    # ------------------------------------------------------------------
    # Evidence fusion weights
    # ------------------------------------------------------------------
    # Must sum to 1.0 — adjust based on validated calibration data
    fusion_weights: Dict[str, float] = field(default_factory=lambda: {
        "detection":  0.25,   # YOLO confidence signal
        "shape":      0.20,   # Geometric regularity
        "texture":    0.15,   # Intensity/texture features
        "shadow":     0.20,   # Acoustic shadow evidence
        "context":    0.10,   # Seabed context contrast
        "uncertainty": 0.10,  # Inverted uncertainty penalty
    })

    # ------------------------------------------------------------------
    # Scoring thresholds
    # ------------------------------------------------------------------
    # Marine Risk Score bands (0–100)
    risk_low_max:      int = 24    # 0–24  = Low
    risk_medium_max:   int = 49    # 25–49 = Medium
    risk_high_max:     int = 74    # 50–74 = High
    # 75–100 = Critical

    # ------------------------------------------------------------------
    # Active learning
    # ------------------------------------------------------------------
    active_learning_dir:       Path = DATA_DIR / "verified"
    retraining_threshold:      int  = 50    # Trigger retraining suggestion after N new samples
    feedback_db_file:          Path = DATA_DIR / "verified" / "feedback.jsonl"

    # ------------------------------------------------------------------
    # Output paths
    # ------------------------------------------------------------------
    output_detections_dir:     Path = OUTPUTS_DIR / "detections"
    output_masks_dir:          Path = OUTPUTS_DIR / "masks"
    output_reports_dir:        Path = OUTPUTS_DIR / "reports"
    output_visualizations_dir: Path = OUTPUTS_DIR / "visualizations"
    logs_dir:                  Path = LOGS_DIR

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------
    log_level: str = "INFO"   # DEBUG | INFO | WARNING | ERROR

    # ------------------------------------------------------------------
    # Dataset split
    # ------------------------------------------------------------------
    split_ratios: Dict[str, float] = field(default_factory=lambda: {
        "train": 0.70,
        "val":   0.15,
        "test":  0.15,
    })

    # ------------------------------------------------------------------
    # Supported input formats
    # ------------------------------------------------------------------
    supported_image_extensions: List[str] = field(default_factory=lambda: [
        ".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp",
    ])

    # ------------------------------------------------------------------
    # Class names (updated when dataset is validated)
    # ------------------------------------------------------------------
    # These are placeholder class names — actual names come from the dataset
    class_names: List[str] = field(default_factory=lambda: [
        "marine_debris",
        "shipwreck",
        "ghost_gear",
        "anomaly",
        "seabed_structure",
    ])

    def __post_init__(self):
        """Ensure all output directories exist and validate weights sum."""
        dirs_to_create = [
            self.data_raw_dir, self.data_processed_dir,
            self.data_train_dir / "images", self.data_train_dir / "labels",
            self.data_val_dir   / "images", self.data_val_dir   / "labels",
            self.data_test_dir  / "images", self.data_test_dir  / "labels",
            self.data_verified_dir,
            self.yolo_model_dir, self.sam_model_dir,
            self.output_detections_dir, self.output_masks_dir,
            self.output_reports_dir, self.output_visualizations_dir,
            self.logs_dir,
        ]
        for d in dirs_to_create:
            d.mkdir(parents=True, exist_ok=True)

        # Validate fusion weights
        weight_sum = sum(self.fusion_weights.values())
        if abs(weight_sum - 1.0) > 1e-6:
            raise ValueError(
                f"fusion_weights must sum to 1.0, got {weight_sum:.4f}. "
                "Fix config.py before running the system."
            )

        # Validate split ratios
        ratio_sum = sum(self.split_ratios.values())
        if abs(ratio_sum - 1.0) > 1e-6:
            raise ValueError(
                f"split_ratios must sum to 1.0, got {ratio_sum:.4f}."
            )

    def device_info(self) -> str:
        """Human-readable device description."""
        if self.device == "cuda":
            name = torch.cuda.get_device_name(0)
            mem  = torch.cuda.get_device_properties(0).total_memory / 1e9
            return f"CUDA GPU: {name} ({mem:.1f} GB)"
        return "CPU (no CUDA detected — using CPU mode)"

    def to_dict(self) -> dict:
        """Serialise config to a plain dict for logging/reporting."""
        result = {}
        for k, v in self.__dict__.items():
            if isinstance(v, Path):
                result[k] = str(v)
            elif isinstance(v, dict):
                result[k] = {dk: (str(dv) if isinstance(dv, Path) else dv)
                             for dk, dv in v.items()}
            else:
                result[k] = v
        return result


# ---------------------------------------------------------------------------
# Module-level singleton for convenience import
# ---------------------------------------------------------------------------
# Usage: from config import cfg
cfg = Config()

