export const GLOBAL_MARINE_REGIONS = [
  {
    id: 'in-bob',
    name: 'India · Bay of Bengal (Survey Track 01)',
    country: 'India',
    lat: 13.1150,
    lon: 80.3400,
    depth_m: 32.0,
    sonar_range_m: 50.0,
  },
  {
    id: 'in-arabian',
    name: 'India · Arabian Sea (Mumbai Offshore)',
    country: 'India',
    lat: 18.9100,
    lon: 72.7800,
    depth_m: 45.0,
    sonar_range_m: 75.0,
  },
  {
    id: 'in-mannar',
    name: 'India · Gulf of Mannar (Coral Marine Park)',
    country: 'India',
    lat: 9.1200,
    lon: 79.2400,
    depth_m: 18.5,
    sonar_range_m: 40.0,
  },
  {
    id: 'in-andaman',
    name: 'India · Andaman Sea (Port Blair Deep Track)',
    country: 'India',
    lat: 11.6600,
    lon: 92.7600,
    depth_m: 65.0,
    sonar_range_m: 100.0,
  },
  {
    id: 'us-gom',
    name: 'United States · Gulf of Mexico (Shelf Zone)',
    country: 'United States',
    lat: 28.5000,
    lon: -88.5000,
    depth_m: 55.0,
    sonar_range_m: 80.0,
  },
  {
    id: 'us-california',
    name: 'United States · Pacific Coast (Channel Islands)',
    country: 'United States',
    lat: 34.0000,
    lon: -119.5000,
    depth_m: 70.0,
    sonar_range_m: 100.0,
  },
  {
    id: 'uk-northsea',
    name: 'United Kingdom · North Sea (Dogger Bank)',
    country: 'United Kingdom',
    lat: 55.5000,
    lon: 3.2000,
    depth_m: 28.0,
    sonar_range_m: 50.0,
  },
  {
    id: 'uk-channel',
    name: 'United Kingdom · English Channel',
    country: 'United Kingdom',
    lat: 50.2000,
    lon: -1.5000,
    depth_m: 40.0,
    sonar_range_m: 60.0,
  },
  {
    id: 'eu-med',
    name: 'Europe · Mediterranean Sea (Ionian Sea)',
    country: 'European Union',
    lat: 37.5000,
    lon: 18.2000,
    depth_m: 85.0,
    sonar_range_m: 100.0,
  },
  {
    id: 'eu-baltic',
    name: 'Europe · Baltic Sea (Bornholm Basin)',
    country: 'European Union',
    lat: 55.3000,
    lon: 15.5000,
    depth_m: 60.0,
    sonar_range_m: 75.0,
  },
  {
    id: 'uae-gulf',
    name: 'Middle East · Persian Gulf (UAE Offshore)',
    country: 'United Arab Emirates',
    lat: 25.5000,
    lon: 54.8000,
    depth_m: 25.0,
    sonar_range_m: 50.0,
  },
  {
    id: 'sea-scs',
    name: 'Southeast Asia · South China Sea',
    country: 'International Waters',
    lat: 14.0000,
    lon: 114.0000,
    depth_m: 110.0,
    sonar_range_m: 120.0,
  },
  {
    id: 'sea-malacca',
    name: 'Southeast Asia · Malacca Strait',
    country: 'Singapore / Malaysia',
    lat: 2.2000,
    lon: 102.1000,
    depth_m: 35.0,
    sonar_range_m: 50.0,
  },
  {
    id: 'aus-gbr',
    name: 'Australia · Great Barrier Reef (Outer Shelf)',
    country: 'Australia',
    lat: -18.2000,
    lon: 147.6000,
    depth_m: 38.0,
    sonar_range_m: 60.0,
  },
  {
    id: 'jp-tokyo',
    name: 'Japan · Tokyo Bay Marine Corridor',
    country: 'Japan',
    lat: 35.3000,
    lon: 139.8000,
    depth_m: 30.0,
    sonar_range_m: 50.0,
  },
];
